# Week 1 notes
* map(function, list, ...)
* Lambda functions
* intro to NumPy

# Map function
* map a function to an iterable(s). (3:15)
* all of the iterables are unpacked and passed into the function.
* lazy evaluation - the values aren't computed until they are inspected, rather returns a reference to a map object.  
* Maps are iterable.

In [113]:
list1 = [1,2,3]
list2 = [-1,0,4]
smallest = map(min, list1, list2)
smallest

In [114]:
print([x for x in smallest])

[-1, 0, 3]


# Lambda functions
Construction: 

`lambda keyword + list of args + colon + single expression`

Note that 
* only a single expression is to be evaluated in a lambda.
* the return value of a lambda is a function reference.

In [8]:
myfunc = lambda x, y: x ** y
myfunc(5,3)

125

In [15]:
# List comprehensions:
mynums = [num for num in range(10)]
evens = [num for num in range(10) if num %2 == 0]
print(mynums, evens)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0, 2, 4, 6, 8]


In [17]:
# Overview of numpy:
import numpy as np
y = np.array([4,5,6])
y

array([4, 5, 6])

In [20]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [22]:
m.shape

(2, 3)

In [24]:
# arange function: pass in start, stop, and step size
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [25]:
# reshape: change dimension of an array (not in-place, use 
# resize for that):
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [26]:
# linspace: tell it how many numbers we want returned, 
# and it will do it for us automatically.
o = np.linspace(0,4,9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [27]:
# resize: change dimensions in-place
o.resize(3,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [29]:
# ones and zeros: return arrays as shown
print(np.ones((3,2)))
print(np.zeros((2,3)))
print(np.eye(3))

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [30]:
# diag: constructs a diagonal array. provide it list of values.
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [32]:
# repeat and repeated values (note differences)
print(np.array([1,2,3] * 3))
print(np.repeat([1,2,3], 3))

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [35]:
# create array from other arrays:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
# stack it vertically with another array:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [39]:
# stack horizontally:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations in numpy

In [44]:
# add, multiply, etc. arrays
x = np.array([1,2,3])
x + y

array([5, 7, 9])

In [45]:
x * y

array([ 4, 10, 18])

In [46]:
x ** y

array([  1,  32, 729])

In [48]:
# dot product:
x.dot(y)

32

In [49]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [50]:
z.shape

(2, 3)

In [52]:
# transpose of array
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [53]:
z.T.shape

(3, 2)

In [54]:
z.dtype

dtype('int64')

In [55]:
# change the datatype in an array:
z = z.astype('f')
z.dtype

dtype('float32')

In [58]:
a = np.array([-4, -2, 1, 3, 5])
a.sum()

3

In [59]:
a.max()

5

In [60]:
a.min()

-4

In [61]:
a.std()

3.2619012860600183

In [63]:
# find the index of a max or min value
print(a.argmax(), a.argmin())


4 0


# indexing and slicing

In [68]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [69]:
# get values by index 
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

# slicing

In [70]:
s[1:5]

array([ 1,  4,  9, 16])

In [72]:
s[-4:]

array([ 81, 100, 121, 144])

In [73]:
s[-5::-2] # start 5th from the end, counting backwards by 2 (stepsize)

array([64, 36, 16,  4,  0])

In [84]:
# 2D arrays
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [85]:
r[2, 2]

14

In [86]:
# get a slice of 3rd row cols 3-6:
r[3, 3:6]

array([21, 22, 23])

In [87]:
# get first two rows except last col:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [88]:
# select every second element from last row:
r[-1, ::2]

array([30, 32, 34])

In [90]:
# conditional indexing and assignment
# return an array that is the values in r that are gt 30
r[r > 30]

array([31, 32, 33, 34, 35])

In [91]:
# cap the original elements of array to 30:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [93]:
# WARNING: create new array from slice of r.  Update values
# to zero.  Note that original array is also changed.
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [94]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [95]:
r # note that r was changed when r2 was changed.

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [96]:
# r.copy() - use copy() to create a copy that can change without 
# affecting the original array.
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [99]:
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating over arrays

In [100]:
# create random int array values btwn 0 & 10, dimension 4x3
test = np.random.randint(0, 10, (4, 3))

In [101]:
for row in test:
    print(row)

[7 5 7]
[8 0 1]
[4 7 6]
[6 9 9]


In [106]:
for i in range(len(test)):
    print(test[i])

[7 5 7]
[8 0 1]
[4 7 6]
[6 9 9]


In [108]:
# enumerate: gives row and index of the row
for i, row in enumerate(test):
    print('row', i, 'is' , row)

row 0 is [7 5 7]
row 1 is [8 0 1]
row 2 is [4 7 6]
row 3 is [6 9 9]


In [109]:
test2 = test ** 2
test2

array([[49, 25, 49],
       [64,  0,  1],
       [16, 49, 36],
       [36, 81, 81]])

In [110]:
# zip: useful to iterate through both arrays 
for i, j in zip(test, test2):
    print(i, ' + ', j, ' = ', i + j)

[7 5 7]  +  [49 25 49]  =  [56 30 56]
[8 0 1]  +  [64  0  1]  =  [72  0  2]
[4 7 6]  +  [16 49 36]  =  [20 56 42]
[6 9 9]  +  [36 81 81]  =  [42 90 90]


some in-lecture quizes/exercises (they are soled below)

In [11]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 
          'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + 
                                           ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: 
                                                    person.split()[0] + 
                                                    ' ' + person.split()[-1], 
                                                    people))

True
True
True
True


True

In [111]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 
          'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [11]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 
          'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + 
                                           ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: 
                                                    person.split()[0] + 
                                                    ' ' + person.split()[-1], 
                                                    people))

True
True
True
True


True